### PR TITLE
Special case codeberg and gitlab readme loading

### LINKED ISSUE #204: Gitlab and Codeberg are CORS restricted and the Readme fails
E.g. 

```
CUE/:1 Access to fetch at 'https://gitlab.com/patopest/Sublime-Text-Cuelang-Syntax/-/raw/master/README.md' from origin 'https://packages.sublimetext.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
readme.js:17  GET https://gitlab.com/patopest/Sublime-Text-Cuelang-Syntax/-/raw/master/README.md net::ERR_FAILED 301 (Moved Permanently)
(anonymous) @ readme.js:17
readme.js:42 Failed to load readme: TypeError: Failed to fetch
    at readme.js:17:3
(anonymous) @ readme.js:42
Promise.catch
(anonymous) @ readme.js:41
```

Since we know that we can still try that in case they change their mind, but on failure we can just display:none the readme div.  

A small micro-web service on CF could solve this as well.

### PR DESCRIPTION
**Pull request by kaste**
Both hubs actually do not allow (hint: CORS) loading the README in the
browser, hence, still be optimistic and try a load, but on failure just
hide the readme section.

Closes #204

### CODE REVIEW

File: static/readme.js [hunk 1]
```diff
@@ -40,7 +40,13 @@ else {
     })
     .catch((err) => {
       console.error('Failed to load readme:', err)
-      target.innerHTML = '😒 the readme failed to load.'
+      if (source.includes('codeberg.org/') || source.includes('gitlab.com/')) {
+        target.style.display = 'none'
+      }
+      else {
+        target.style.textAlign = 'center'
+        target.innerHTML = '😒<br>the readme failed to load.'
```
Comment (braver) [inline static/readme.js]:
```suggestion
        target.innerHTML = '😒<br>The readme failed to load.'
```

Image
